version: '3.4'

services:

  js:
    build: ./js
    container_name: ${PROJECT_NAME:-project}-js
    env_file:
      - ../envs/.env-${GITHUB_REPOSITORY_NAME}
    environment:
      APP_PORT: 3310
      APP_SECRET: ${APP_SECRET:-123456789}
      FRONTEND_URL: "https://${PROJECT_NAME}.${HOST}"
      DB_HOST: ${DATABASE_SUBDOMAIN_NAME}-db
      DB_PORT: 3306
      DB_USER: ${USER_NAME}
      DB_PASSWORD: ${USER_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT_NAME:-project}-js-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME:-project}-js-secure.rule=Host(`${PROJECT_NAME:-project}-js.${HOST:-localhost}`)"
      - "traefik.http.services.${PROJECT_NAME:-project}-js.loadbalancer.server.port=3310"

networks:
  proxy:
    external: true
